// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TransactionRiskEngine.Api.Data;

#nullable disable

namespace TransactionRiskEngine.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TransactionRiskEngine.Api.Domain.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntityCode")
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Summary")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("TransactionRecordId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("TransactionRecordId");

                    b.HasIndex("EntityType", "EntityCode");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("TransactionRiskEngine.Api.Domain.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsFlagged")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.HasIndex("Fingerprint")
                        .IsUnique();

                    b.ToTable("Devices", (string)null);
                });

            modelBuilder.Entity("TransactionRiskEngine.Api.Domain.FraudCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<Guid>("TransactionRecordId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("TransactionRecordId")
                        .IsUnique();

                    b.ToTable("FraudCases", (string)null);
                });

            modelBuilder.Entity("TransactionRiskEngine.Api.Domain.IpAddressRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsFlagged")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Address")
                        .IsUnique();

                    b.ToTable("IpAddresses", (string)null);
                });

            modelBuilder.Entity("TransactionRiskEngine.Api.Domain.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("LockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.HasIndex("Status", "LockedAt");

                    b.HasIndex("Status", "AttemptCount", "NextAttemptAt", "OccurredAt");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("TransactionRiskEngine.Api.Domain.PaymentCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsFlagged")
                        .HasColumnType("boolean");

                    b.Property<string>("Last4")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.HasKey("Id");

                    b.HasIndex("Fingerprint")
                        .IsUnique();

                    b.ToTable("PaymentCards", (string)null);
                });

            modelBuilder.Entity("TransactionRiskEngine.Api.Domain.RiskEvaluationJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChangedCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProcessedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("RequestedBatchSize")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("RiskEvaluationJobs", (string)null);
                });

            modelBuilder.Entity("TransactionRiskEngine.Api.Domain.RiskEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BaseScore")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<Guid>("TransactionRecordId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TransactionRecordId");

                    b.ToTable("RiskEvents", (string)null);
                });

            modelBuilder.Entity("TransactionRiskEngine.Api.Domain.RiskRule", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Code");

                    b.ToTable("RiskRules", (string)null);
                });

            modelBuilder.Entity("TransactionRiskEngine.Api.Domain.TransactionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)");

                    b.Property<Guid?>("IpAddressRecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("Merchant")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<Guid?>("PaymentCardId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequestHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("RiskScore")
                        .HasColumnType("integer");

                    b.Property<bool>("Successful")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Decision");

                    b.HasIndex("DeviceId");

                    b.HasIndex("IpAddressRecordId");

                    b.HasIndex("PaymentCardId");

                    b.HasIndex("RiskScore");

                    b.HasIndex("UserProfileId", "CreatedAt");

                    b.HasIndex("UserProfileId", "IdempotencyKey")
                        .IsUnique()
                        .HasFilter("\"IdempotencyKey\" IS NOT NULL");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("TransactionRiskEngine.Api.Domain.UserCard", b =>
                {
                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PaymentCardId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserProfileId", "PaymentCardId");

                    b.HasIndex("PaymentCardId");

                    b.ToTable("UserCards", (string)null);
                });

            modelBuilder.Entity("TransactionRiskEngine.Api.Domain.UserDevice", b =>
                {
                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserProfileId", "DeviceId");

                    b.HasIndex("DeviceId");

                    b.ToTable("UserDevices", (string)null);
                });

            modelBuilder.Entity("TransactionRiskEngine.Api.Domain.UserIpAddress", b =>
                {
                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IpAddressRecordId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserProfileId", "IpAddressRecordId");

                    b.HasIndex("IpAddressRecordId");

                    b.ToTable("UserIpAddresses", (string)null);
                });

            modelBuilder.Entity("TransactionRiskEngine.Api.Domain.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsFlagged")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("TransactionRiskEngine.Api.Domain.AuditLog", b =>
                {
                    b.HasOne("TransactionRiskEngine.Api.Domain.TransactionRecord", "TransactionRecord")
                        .WithMany("AuditLogs")
                        .HasForeignKey("TransactionRecordId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TransactionRecord");
                });

            modelBuilder.Entity("TransactionRiskEngine.Api.Domain.FraudCase", b =>
                {
                    b.HasOne("TransactionRiskEngine.Api.Domain.TransactionRecord", "TransactionRecord")
                        .WithOne("FraudCase")
                        .HasForeignKey("TransactionRiskEngine.Api.Domain.FraudCase", "TransactionRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TransactionRecord");
                });

            modelBuilder.Entity("TransactionRiskEngine.Api.Domain.RiskEvent", b =>
                {
                    b.HasOne("TransactionRiskEngine.Api.Domain.TransactionRecord", "TransactionRecord")
                        .WithMany("RiskEvents")
                        .HasForeignKey("TransactionRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TransactionRecord");
                });

            modelBuilder.Entity("TransactionRiskEngine.Api.Domain.TransactionRecord", b =>
                {
                    b.HasOne("TransactionRiskEngine.Api.Domain.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId");

                    b.HasOne("TransactionRiskEngine.Api.Domain.IpAddressRecord", "IpAddressRecord")
                        .WithMany()
                        .HasForeignKey("IpAddressRecordId");

                    b.HasOne("TransactionRiskEngine.Api.Domain.PaymentCard", "PaymentCard")
                        .WithMany()
                        .HasForeignKey("PaymentCardId");

                    b.HasOne("TransactionRiskEngine.Api.Domain.UserProfile", "UserProfile")
                        .WithMany("Transactions")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("IpAddressRecord");

                    b.Navigation("PaymentCard");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("TransactionRiskEngine.Api.Domain.UserCard", b =>
                {
                    b.HasOne("TransactionRiskEngine.Api.Domain.PaymentCard", "PaymentCard")
                        .WithMany("Users")
                        .HasForeignKey("PaymentCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TransactionRiskEngine.Api.Domain.UserProfile", "UserProfile")
                        .WithMany("Cards")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentCard");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("TransactionRiskEngine.Api.Domain.UserDevice", b =>
                {
                    b.HasOne("TransactionRiskEngine.Api.Domain.Device", "Device")
                        .WithMany("Users")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TransactionRiskEngine.Api.Domain.UserProfile", "UserProfile")
                        .WithMany("Devices")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("TransactionRiskEngine.Api.Domain.UserIpAddress", b =>
                {
                    b.HasOne("TransactionRiskEngine.Api.Domain.IpAddressRecord", "IpAddressRecord")
                        .WithMany("Users")
                        .HasForeignKey("IpAddressRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TransactionRiskEngine.Api.Domain.UserProfile", "UserProfile")
                        .WithMany("IpAddresses")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IpAddressRecord");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("TransactionRiskEngine.Api.Domain.Device", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("TransactionRiskEngine.Api.Domain.IpAddressRecord", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("TransactionRiskEngine.Api.Domain.PaymentCard", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("TransactionRiskEngine.Api.Domain.TransactionRecord", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("FraudCase");

                    b.Navigation("RiskEvents");
                });

            modelBuilder.Entity("TransactionRiskEngine.Api.Domain.UserProfile", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("Devices");

                    b.Navigation("IpAddresses");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
